#!/bin/bash
# Script created by Rainer Rössler (roesslerrr-at-web.de)
# License: Free Software (License GPLv3)

cd ~

HEIMAT=`pwd`
echo $HEIMAT > /tmp/heimatverzeichnis
chmod 777 /tmp/heimatverzeichnis
