#!/usr/bin/perl -w
# This Script (linuxmuster-client-extras-setup) was created by Rüdiger Beck
# It is released under the GPL Version 3
# For Bugs send mail to (jeffbeck-at-web.de)

use strict;
use Getopt::Long;
use File::Basename;


my $old_script_warning=0;
my $config_dir="/etc/linuxmuster-client-extras/login-enabled";

# The following file: 
# /etc/xdg/autostart/linuxmuster-client-extra.desktop
# --> nicht im Paket, sondern beim aufruf von linuxmuster-client-extras-setup 
# kopieren aus /usr/share/Paket (Permissions setzen)
# ... starts  linuxmuster-client-extras-login when logging in (with user permissions)
# What is run is in directory /etc/linuxmuster-client-extras/login-enabled
# In this dir are links (with a number, to ensure order of execution) to scripts 
# in /usr/bin/... that are run 
#
# with linuxmuster-client-extras-setup you can add/remove/list, .... all these links
# Check the following:
#   - Show dead links
#   - Show nondead links that are added manually by the admin
#
# ??? Is there something similar for logoff
#
#
# Einschalten eines scripts:
# linuxmuster-client-extras-setup --on /usr/bin/italc-raumanpassung.sh
#     1)  schauen in der map, wie der Link heisst
#     2) -x checken 
#     3) link anlegen
# wenn Link nicht in der Map: ERROR
# option --order 010     (3stelliger wert erforderlich)
#
# Aus schalten eines scripts:
# linuxmuster-client-extras-setup --off 010
#     1) link entfernen
#
#
# --info
#
# 1) Possible Scripts with explanation
#
# 2) Known Linked Scripts (Link Target UND linkname in map)
# Zeigt  linkname -> script_pfad_absolute
# 3) Unknown Linked Scripts (Please register them)
# Zeigt  linkname -> script_pfad_absolute


my $help=0;
# just for testing
#my @old_scripts=("/usr/bin/ahjdsahdask",
#                ); 

my @old_scripts=(
    "/usr/bin/watch-my-home", 
    "/usr/bin/standarddrucker-nach-raum.sh", 
    "/usr/bin/italc-raumanpassung.sh", 
    "/usr/bin/herunterfahren.sh", 
    "/usr/bin/desktop-icons-hinzu.sh", 
    "/usr/bin/ausdruck-winxp-splitter", 
    "/usr/bin/ausdruck-winxp-spooler", 
    "/usr/bin/leoclient-admin", 
   );

my @old_script_warning_lines=("\nWARNING:\n The following files are replaced by the linuxmuster-client-extras package.\n You should delete them:\n");


my %script_link_map = (
    "/usr/bin/watch-my-home", "/etc/linuxmuster-client-extras/login-enabled/010-watch-my-home", 
    "/usr/bin/standarddrucker-nach-raum.sh",  "/etc/linuxmuster-client-extras/login-enabled/020-set-default-printer", 
    "/usr/bin/italc-raumanpassung.sh",  "/etc/linuxmuster-client-extras/login-enabled/030-set-italc-rooms",
#    "/usr/bin/herunterfahren.sh",  "/etc/sc4",
#    "/usr/bin/desktop-icons-hinzu.sh",  "/etc/sc5",
#    "/usr/bin/ausdruck-winxp-splitter",  "/etc/sc6",
#    "/usr/bin/ausdruck-winxp-spooler",  "/etc/sc7",
#    "/usr/bin/leoclient-admin",  "/etc/sc8",
   );




# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
          );

# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);



if ($help==1){
   print('
Options
  -h  / --help
');
   print "\n";
   exit;
}


# Checking for old scripts
foreach my $file (@old_scripts) {
    if (-e $file){
        $old_script_warning=1;
        push  @old_script_warning_lines , "    $file\n";
    }
}
if ($old_script_warning==1){
    foreach my $line (@old_script_warning_lines) {
        print $line;
    }
    print "\n";
}


# Creating Links
# make sure Directory exists

if (not -d $config_dir){
    system("mkdir -p $config_dir");
    # ????? set permissions
}

while (my ($script,$linkname) = each %script_link_map){
    print "Creating Link:\n";
    print "$linkname -> $script\n";
    if (-l $linkname){
        system("rm $linkname");
    }

    symlink $script, $linkname;
}





############################################################
# subs
############################################################
sub  check_options{
   my ($parse_ergebnis) = @_;
   if (not $parse_ergebnis==1){
      my @list = split(/\//,$0);
      my $scriptname = pop @list;
      print "\nYou have made a mistake, when specifying options.\n"; 
      print "See error message above. \n\n";
      print "... $scriptname is terminating.\n\n";
      exit;
   } else {
      print "All options  were recognized.\n";
   }

}

