#!/bin/bash
# Script created by Rainer Rössler (roesslerrr-at-web.de)
# License: Free Software (License GPLv3)

RECHNER=`hostname`

# symbolischer Link .italc im Heimatverzeichnis löschen, falls vorhanden
if [ -h "$HOME/.italc" ]; then
  rm "$HOME/.italc"
fi

# Verzeichnis .italc im Heimatverzeichnis wegsichern, falls vorhanden
if [ -d "$HOME/.italc" ]; then
  # Verzeichnis .italc-alt im Heimatverzeichnis loeschen, falls vorhanden
  if [ -d "$HOME/.italc-alt" ]; then
    rm -rf "$HOME/.italc-alt"
  fi
  mv "$HOME/.italc" "$HOME/.italc-alt"
fi

# neuer symbolischer link erzeugen, falls Ziel existiert
if [ -d "/home/share/teachers/.italc/$RECHNER" ]; then
  ln -s "/home/share/teachers/.italc/$RECHNER" "$HOME/.italc"
fi
